### ISSUE TITLE
Homeroom Scripts Missing from Workshop After Most Recent Scripts Update

### ISSUE THREAD

**Issue by danielhelfand** [openshift-labs/lab-tekton-pipelines#63]
It appears that the most [recent scripts update](https://github.com/openshift-labs/lab-tekton-pipelines/commit/3dc612841411181e65df6ca8d0abad3bbcb6b07f) to the workshop has removed the shell scripts under `.workshop/scripts/`. 

cc @GrahamDumpleton

**Comment by danielhelfand** [comment]
I didn't realize `git submodule update --init --recursive` needed to be run each time off of a direct clone. Previously I had forked the repo so that appears to be the issue.

**Comment by GrahamDumpleton** [comment]
Or when you use `git clone` you pass it `--recurse-submodules`. It is mentioned in the README file.
