### ISSUE TITLE
lab-tekton-pipelines-workshops pod asks for privileged permission 

### ISSUE THREAD

**Issue by blues-man** [openshift-labs/lab-tekton-pipelines#64]
Hello, I followed the README but after launching `.workshop/scripts/deploy-spawner.sh` script I got this error:
```
### Install static resource definitions.
the namespace from the provided object "openshift-marketplace" does not match the namespace "workshops". You must pass '--namespace=openshift-marketplace' to perform this operation.
the namespace from the provided object "openshift-operators" does not match the namespace "workshops". You must pass '--namespace=openshift-operators' to perform this operation.
Error: Failed to create static resource definitions. 
```
From the Workshop Dashboard when Launching the Server I got:

`Reason: error
HTTP response headers: HTTPHeaderDict({'Audit-Id': '140d7d5d-5650-4abf-8d8b-73bed1939c20', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Mon, 07 Oct 2019 14:46:00 GMT', 'Content-Length': '413'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"lab-tekton-pipelines-workshops-sx9n8\" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]","reason":"Forbidden","details":{"name":"lab-tekton-pipelines-workshops-sx9n8","kind":"pods"},"code":403}`

so I tried to give the permission to the ServiceAccount:

```bash
 oc adm policy add-scc-to-user privileged -z lab-tekton-pipelines-workshops-hub
```

Server starts but then Workshop content is empty:

![Screenshot_20191007_170420](https://user-images.githubusercontent.com/1446126/66323764-95a19580-e924-11e9-9768-799e85a4ae56.png)

Tested on OCP 4.2 Beta

```
$ oc get clusterversion
NAME      VERSION                             AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.2.0-0.nightly-2019-10-01-210901   True        False         5h51m   Cluster version is 4.2.0-0.nightly-2019-10-01-210901
```

Am I missing something?

Thanks!

**Comment by jorgemoralespou** [comment]
cc/ @GrahamDumpleton

**Comment by danielhelfand** [comment]
This is unfortunately an issue on 4.1 as well. 

@jorgemoralespou has pointed out that a new requirement for using `oc apply` when creating resources in a different namespace than the one you are working in is to explicitly use the `--namepsace` or `-n` option to specify where to create the resource. 

@blues-man If you are interested in viewing the workshop before a fix is put in place, I have a [fork](https://github.com/danielhelfand/lab-tekton-pipelines) of this repo that uses old deployment scripts that appear to work. You should just be able to clone it, run `oc new-project workshops`, and run `.workshop/scripts/deploy-spawner`. This however will only work on 4.1.

**Comment by danielhelfand** [comment]
Workaround for 4.1 is to remove `-n "$PROJECT_NAME"` from [deploy-spawner.sh](https://github.com/openshift-homeroom/workshop-scripts/blob/0150ae160054fe58465691564c3d9d101ca59ad6/deploy-spawner.sh#L277)

However, getting the following issue for trying to deploy to 4.2 cluster with workaround:

```
### Install static resource definitions.
subscription.operators.coreos.com/openshift-pipelines-operator created
The CatalogSourceConfig "installed-openshift-pipelines" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"operators.coreos.com/v1", "kind":"CatalogSourceConfig", "metadata":map[string]interface {}{"annotations":map[string]interface {}{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"operators.coreos.com/v1\",\"kind\":\"CatalogSourceConfig\",\"metadata\":{\"annotations\":{},\"name\":\"installed-openshift-pipelines\",\"namespace\":\"openshift-marketplace\"},\"spec\":{\"csDisplayName\":\"Community Operators\",\"csPublisher\":\"Community\",\"packages\":\"openshift-pipelines-operator\",\"targetNamespace\":\"openshift-operators\"}}\n"}, "creationTimestamp":"2019-10-07T18:50:20Z", "generation":1, "name":"installed-openshift-pipelines", "namespace":"openshift-marketplace", "uid":"4fe75705-e933-11e9-b559-12194ecd6e20"}, "spec":map[string]interface {}{"csDisplayName":"Community Operators", "csPublisher":"Community", "packages":"openshift-pipelines-operator", "targetNamespace":"openshift-operators"}}: validation failure list:
spec.source in body is required
Error: Failed to create static resource definitions.
```

**Comment by GrahamDumpleton** [comment]
See https://github.com/openshift-homeroom/workshop-scripts/issues/7

**Comment by danielhelfand** [comment]
This should be resolved by @GrahamDumpleton's updated scripts and [setting the source property](https://github.com/openshift-labs/lab-tekton-pipelines/commit/a3ba6602a2777e8949fb606ceb8687e78d52ed80) for the operator resource definition to `community-operators`.
