### ISSUE TITLE
Operator update channel, deployment names

### ISSUE THREAD

**Issue by kwkoo** [openshift-labs/lab-tekton-pipelines#83]
1. The current stable version (early June 2021) of the pipelines operator does not work on learn.openshift.com - it would only work when I set the update channel to ocp-4.6

2. `workshop/content/06trigger-pipeline.adoc` start the pipelines with `-p deployment-name=vote-api` and `-p deployment-name=vote-ui`. These should be updated to `-p deployment-name=pipelines-vote-api` and `-p deployment-name=pipelines-vote-ui` respectively.

**Comment by blues-man** [comment]
Hello, this looks more like a learn.openshift.com scenario issue, this project is only for the RHPDS lab which is working correctly because it points to OCP 4.6.

Can you open an issue here: https://github.com/openshift-labs/learn-katacoda/issues ?
